//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ĐACN
{
    using System;
    using System.Collections.Generic;
    
    public partial class DanhGiaShipper
    {
        public string MaDG { get; set; }
        public string MaDon { get; set; }
        public string MaKH { get; set; }
        public string MaShipper { get; set; }
        public Nullable<int> SoSao { get; set; }
        public string BinhLuan { get; set; }
        public Nullable<System.DateTime> ThoiGian { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual Shipper Shipper { get; set; }
        public virtual KhachHang KhachHang { get; set; }
    }
}
